export const SELECT_COLOR = 'SELECT_COLOR'
export const SELECT_SIZE = 'SELECT_SIZE'
export const SELECT_TYPES = 'SELECT_TYPES'
export const SELECT_PRICE = 'SELECT_PRICE'
export const FILTER = 'FILTER'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const SHOW_CART = 'SHOW_CART'
